<a href="https://colab.research.google.com/github/Shiv12GitHub39G/PCS-221/blob/main/Cloud_Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Q1
import numpy as np
import pandas as pd


In [ ]:
rows = 20000
cols = 10000

# generate data (float32 to reduce memory)
data = np.random.uniform(0, 100, size=(rows, cols)).astype(np.float32)

# save in binary format
np.save("large_dataset.npy", data)

print("File created successfully!")

File created successfully!


In [ ]:
# Q2
import numpy as np

# Create sample matrix
matrix = np.random.randint(1,10,(4,5))

print("Original Matrix:\n", matrix)

# Assign all subsequent rows to first row
matrix[1:, :] = matrix[0, :]

print("\nModified Matrix:\n", matrix)


Original Matrix:
 [[9 3 2 2 4]
 [7 5 8 3 2]
 [7 3 1 3 7]
 [4 1 8 4 3]]

Modified Matrix:
 [[9 3 2 2 4]
 [9 3 2 2 4]
 [9 3 2 2 4]
 [9 3 2 2 4]]


In [ ]:
# Q3
import numpy as np

data = np.array([1,2,1,3,2,1,4,3,6])

unique_vals = np.unique(data)

groups = [data[data == val] for val in unique_vals]

print("Grouped Elements:")
for row in groups:
    print(row)


Grouped Elements:
[1 1 1]
[2 2]
[3 3]
[4]
[6]


In [ ]:
# Q4
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print(f"Enter {rows} rows for Matrix A, each with {cols} elements separated by spaces:")
A = []
for i in range(rows):
    while True:
        try:
            row_input = list(map(int, input().split()))
            if len(row_input) == cols:
                A.append(row_input)
                break
            else:
                print(f"Please enter exactly {cols} elements for this row. Try again.")
        except ValueError:
            print("Invalid input. Please enter integers separated by spaces. Try again.")

print(f"Enter {rows} rows for Matrix B, each with {cols} elements separated by spaces:")
B = []
for i in range(rows):
    while True:
        try:
            row_input = list(map(int, input().split()))
            if len(row_input) == cols:
                B.append(row_input)
                break
            else:
                print(f"Please enter exactly {cols} elements for this row. Try again.")
        except ValueError:
            print("Invalid input. Please enter integers separated by spaces. Try again.")

add_result = [[0]*cols for _ in range(rows)]
sub_result = [[0]*cols for _ in range(rows)]

for i in range(rows):
    for j in range(cols):
        add_result[i][j] = A[i][j] + B[i][j]
        sub_result[i][j] = A[i][j] - B[i][j]

print("\nAddition Result:")
for row in add_result:
    print(row)

print("\nSubtraction Result:")
for row in sub_result:
    print(row)


Enter number of rows: 3
Enter number of columns: 3
Enter 3 rows for Matrix A, each with 3 elements separated by spaces:
1 2 3
4 5 6
7 8 9
Enter 3 rows for Matrix B, each with 3 elements separated by spaces:
2 5 7 
8 6 4
1 8 3

Addition Result:
[3, 7, 10]
[12, 11, 10]
[8, 16, 12]

Subtraction Result:
[-1, -3, -4]
[-4, -1, 2]
[6, 0, 6]


In [ ]:
# Q5
def create_matrix(n):
    matrix = [[(i + j) for j in range(n)] for i in range(n)]
    return matrix

# Input
n = int(input("Enter value of n: "))

# Generate matrix
matrix = create_matrix(n)

# Print matrix
print("\nGenerated Matrix:")
for row in matrix:
    print(row)


Enter value of n: 5

Generated Matrix:
[0, 1, 2, 3, 4]
[1, 2, 3, 4, 5]
[2, 3, 4, 5, 6]
[3, 4, 5, 6, 7]
[4, 5, 6, 7, 8]


In [ ]:
# Q6
# tuple matrix
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

# row-wise sum
row_sums = tuple(sum(row) for row in matrix)

print("Row-wise sums:", row_sums)


Row-wise sums: (6, 15, 24)
