<a href="https://colab.research.google.com/github/Shiv12GitHub39G/PCS-221/blob/main/Cloud_Lab_Assignment_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1 - Create a data file by using python random module with different random generator parameters. The data file must have 20000 * 10000 (rows * columns) in the data file. This data file to be used as database for realization of math and matrix operations in cloud computing lab assignments.

In [ ]:
import numpy as np
import pandas as pd
rows = 20000
cols = 10000

# generate data (float32 to reduce memory)
data = np.random.uniform(0, 100, size=(rows, cols)).astype(np.float32)

# save in binary format
np.save("large_dataset.npy", data)

print("File created successfully!")

File created successfully!


Q2 Write a program in python to assign subsequent rows to matrix first row elements.

In [ ]:
import numpy as np

# Create sample matrix
matrix = np.random.randint(1,10,(4,5))

print("Original Matrix:\n", matrix)

# Assign all subsequent rows to first row
matrix[1:, :] = matrix[0, :]

print("\nModified Matrix:\n", matrix)


Original Matrix:
 [[7 2 9 7 6]
 [6 5 7 6 9]
 [5 6 8 9 7]
 [5 6 1 7 5]]

Modified Matrix:
 [[7 2 9 7 6]
 [7 2 9 7 6]
 [7 2 9 7 6]
 [7 2 9 7 6]]


Q3 - Write a program in python to group similar elements into matrix.

In [ ]:
import numpy as np

data = np.array([1,2,1,3,2,1,4,3,6])

unique_vals = np.unique(data)

groups = [data[data == val] for val in unique_vals]

print("Grouped Elements:")
for row in groups:
    print(row)


Grouped Elements:
[1 1 1]
[2 2]
[3 3]
[4]
[6]


Q4 - Write a program in python to add and subtract matrices in python.

In [ ]:
rows = int(input("Enter number of rows: "))
cols = int(input("Enter number of columns: "))

print(f"Enter {rows} rows for Matrix A, each with {cols} elements separated "
      "by spaces:")
A = []
for i in range(rows):
    while True:
        try:
            row_input = list(map(int, input().split()))
            if len(row_input) == cols:
                A.append(row_input)
                break
            else:
                print(f"Enter {cols} elements per row. Try again.")
        except ValueError:
            print("Invalid input. Integers only. Try again.")

print(f"Enter {rows} rows for Matrix B, each with {cols} elements separated "
      "by spaces:")
B = []
for i in range(rows):
    while True:
        try:
            row_input = list(map(int, input().split()))
            if len(row_input) == cols:
                B.append(row_input)
                break
            else:
                print(f"Enter {cols} elements per row. Try again.")
        except ValueError:
            print("Invalid input. Integers only. Try again.")

add_result = [[0]*cols for _ in range(rows)]
sub_result = [[0]*cols for _ in range(rows)]

for i in range(rows):
    for j in range(cols):
        add_result[i][j] = A[i][j] + B[i][j]
        sub_result[i][j] = A[i][j] - B[i][j]

print("\nAddition Result:")
for row in add_result:
    print(row)

print("\nSubtraction Result:")
for row in sub_result:
    print(row)


Enter number of rows: 3
Enter number of columns: 3
Enter 3 rows for Matrix A, each with 3 elements separated by spaces:
1 2 3
4 5 6
7 8 9
Enter 3 rows for Matrix B, each with 3 elements separated by spaces:
2 3 4
6 5 4
1 2 4

Addition Result:
[3, 5, 7]
[10, 10, 10]
[8, 10, 13]

Subtraction Result:
[-1, -1, -1]
[-2, 0, 2]
[6, 6, 5]


Q5 - Write a program in python to create a n*n square matrix, where all the sub-matrix has the sum of opposite corner elements as even.

In [ ]:
def create_matrix(n):
    matrix = [[(i + j) for j in range(n)] for i in range(n)]
    return matrix

# Input
n = int(input("Enter value of n: "))

# Generate matrix
matrix = create_matrix(n)

# Print matrix
print("\nGenerated Matrix:")
for row in matrix:
    print(row)


Enter value of n: 6

Generated Matrix:
[0, 1, 2, 3, 4, 5]
[1, 2, 3, 4, 5, 6]
[2, 3, 4, 5, 6, 7]
[3, 4, 5, 6, 7, 8]
[4, 5, 6, 7, 8, 9]
[5, 6, 7, 8, 9, 10]


Q6 - Write a program in python to perform row-wise element addition in tuple matrix.

In [ ]:
matrix = (
    (1, 2, 3),
    (4, 5, 6),
    (7, 8, 9)
)

# row-wise sum
row_sums = tuple(sum(row) for row in matrix)

print("Row-wise sums:", row_sums)


Row-wise sums: (6, 15, 24)
